########################################################
#    KinetechConcepts.com                              #
#    Master Keys List!!                                #
# ==================================================== #
# Application: Python Key: value for options class.    #
#   - options.key = value                              #
########################################################

#=====| LAST UPDATED: Feb. 5, 18 |======#

#//////| APP |\\\\\\#
verbose: True
user_email: 'eric.alphagriffin@gmail.com'
notify_by_mail: False

#//////| PRINTER |\\\\\\#
border: '|~|'
filler: ' '
spacer: ' |#|'
blocker: '    '

#//////| SpreadSheets |\\\\\\#
google_api: ''
google_client_id: '?????.apps.googleusercontent.com'
google_client_secret: ''

#//////| EXCHANGES |\\\\\\#
# Binance.com
binance_api: ''
binance_secret: ''

# Bitmex.com
bitmex_api: ''
bitmex_secret: ''

# Hitbtc.com
hitbtc_api: ''
hitbtc_secret: ''

# livecoin.com
livecoin_api_url: 'https://api.livecoin.net'
livecoin_api: ''
livecoin_secret: ''

# Poloniex.com
poloniex_api: ''
poloniex_secret: ''

# Cryptopia.com
cryptopia_api: ''
cryptopia_secret: ''

# C-cex.com
ccex_api: ''
ccex_secret: ''

# Bittrex.com
bittrex_api: ''
bittrex_secret: ''


#//////| MINING POOLS |\\\\\\#
# Blockfactory.com
blockfactory_api: ''

# suprnova.cc
suprnovaETN_url: 'https://etn.sup.rnova.cc/index.php?page=api&action=getuserstatus&api_key='
suprnovaETN_api: ''
suprnovaETN_id: ''

# NICEHASH.com
nicehash_api_id: ''
nicehash_api: ''
nicehash_btc_addr: ''

#//////| BitTensor |\\\\\\#
# Data Collection options
use_exchanges: 'poloniex'     # Polo has all the options available, some exchanges do not.
# use_pairs: 'DASH/BTC,LTC/BTC,ETH/BTC,XMR/BTC'
use_pairs: 'LTC/BTC'
use_start_date: '2017-11-05 16:20:00'
# make these static.
use_period: '5m'              # 5m is the min for polo maybe others
use_msec: 1000                # this should be static
use_period_msecs: 300000      # as should this, be static also


## Tensorflow options  # increasing these numbers dramatically increases training time!
num_gpus: 0

# Price Prediction Network
P_num_layers: 4                # this is the 'Deep' part of deep learning
P_max_nuerons: 1024            # this is complexity

# Q Network
Q_num_layers: 4                # this is the 'Deep' part of deep learning
Q_max_nuerons: 1024            # this is complexity
