########################################################
#    KinetechConcepts.com                              #
#    Master Keys List!!                                #
# ==================================================== #
# Application: Python Key: value for options class.    #
#   - options.key = value                              #
########################################################

#=====| LAST UPDATED: Dec. 2, 18 |======#

#//////| APP |\\\\\\#
verbose: True
user_email: 'eric.alphagriffin@gmail.com'
notify_by_mail: False

#//////| PRINTER |\\\\\\#
border: '|~|'
filler: ' '
spacer: '~|#|~'
blocker: '    '

#//////| SpreadSheets and Storage |\\\\\\#
google_api: 'YOUR INFO HERE'
google_client_id: 'YOUR INFO HERE'
google_client_secret: 'YOUR INFO HERE'

#//////| EXCHANGES |\\\\\\#
# Poloniex.com
poloniex_api: 'YOUR INFO HERE'
poloniex_secret: 'YOUR INFO HERE'

# Bittrex.com
bittrex_2fac: 'YOUR INFO HERE'
bittrex_api: 'YOUR INFO HERE'
bittrex_secret: 'YOUR INFO HERE'

exchanges: 'bittrex'
